name: 'RELEASE TEST'
on:
  push:
    tags:
    - 'v*'
jobs:
  release:
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@master
      with:
        fetch-depth: 0
      
    - name: Build Changelog
      id: generatechangelog
      uses: mikepenz/release-changelog-builder-action@v3.4.0
      with:
        configuration: "configuration.json"
        ignorePreReleases: "true"
        token: ${{ secrets.GTOKEN }}
    
    - name: Make release
      id: release
      uses: softprops/action-gh-release@master
      with:
        #tag_name: ${{ format('v{0}', needs.checkversion.outputs.version) }}
        tag_name: ${{ github.ref_name }}
        name: ${{ github.ref_name }}
        body: ${{ steps.generatechangelog.outputs.changelog }}
      env:
        GITHUB_TOKEN: ${{ secrets.TOKEN }}
     